openmoko-sound-system2: * supply --no-cpu-limit to pulseaudio to prevent shutting down on overload (which is more likely to happen on embedded systems). closes OM #1010 - thanks Robert Schuster. * rework start script to use startstopdaemon. closes OM #785 - thanks Kristian Mueller.

diff --git a/packages/openmoko2/openmoko-sound-system2/pulseaudio b/packages/openmoko2/openmoko-sound-system2/pulseaudio
--- a/packages/openmoko2/openmoko-sound-system2/pulseaudio
+++ b/packages/openmoko2/openmoko-sound-system2/pulseaudio
@@ -13,17 +13,21 @@ RETVAL=0
 prog="pulseaudio"
 
 start() {
-    echo -n "Starting the audio server..."
+    echo -n "Starting audio server: "
     # FIXME once alsa/shm permissions have been fixed, supply --system
-	pulseaudio --resample-method=trivial -D -nF /etc/pulse/session
-	echo $prog
+    start-stop-daemon -S -x /usr/bin/pulseaudio -- --no-cpu-limit --resample-method=trivial -D -nF /etc/pulse/session
+
+    if [ $? = 0 ]; then
+        echo "$prog (warning ignores)." # FIXME remove comment on warning
+    else
+        echo "(failed.)"
+    fi
 }
 
 stop() {
-	# Stop daemons.
-	echo -n "Shutting down $prog: "
-	killall pulseaudio
-    echo "done"
+    echo -n "Stopping audio server: "
+    start-stop-daemon -K -x /usr/bin/pulseaudio
+    echo "pulseaudio."
 }
 
 # See how we were called.
