altboot: - 40-bootNFS: Copy resolv.conf from flash into pivot_root to allow working DNS - Allowing to use altboot as init inside a pivot_root. Which means as soon as th  e new root is booted, you are presented with altboots menu again. But this ti   me changing behaviour of the pivot_root booting sequence - Improved detected if altboot is run by user (to switch runlevels manually) or   kernel. - Do not run scripts in /etc/altboot.rc if altboot is not enabled - Add Advanced/Boot original INIT. Note: "Normal Boot" might be different than   the real /sbin/init on some machines.

diff --git a/packages/altboot/files/altboot-menu/Advanced/40-bootNFS b/packages/altboot/files/altboot-menu/Advanced/40-bootNFS
--- a/packages/altboot/files/altboot-menu/Advanced/40-bootNFS
+++ b/packages/altboot/files/altboot-menu/Advanced/40-bootNFS
@@ -95,6 +95,7 @@ run_module() {
 		
 		while test -z "$selection"
 		do
+			stty echo
 			echo -n "Boot NFS root: "
 			read junk < /dev/tty1
 			
@@ -118,6 +119,10 @@ run_module() {
 	
 	echo -n "Mounting NFS root..."
 	mount -t nfs "$selection" /media/nfsroot && echo ok || die "mount -t nfs "$selection" /media/nfsroot failed!"
+	
+	# Use configured resolv.conf in the pivoted rootfs
+	echo -n "Copying resolv.conf..."
+	cp /etc/resolv.conf /media/nfsroot/etc >/dev/null 2>&1 && echo ok || echo "FAILED"
 	
 	check_target "/media/nfsroot"
 	
