squid: revamp init
Configure squid to create PID file by default, use SQUID_ARGS variable,
wait for it to actually stop when stopping (takes some time for squid
to do it).

Signed-off-by: Roman I Khimov <khimov@altell.ru>

diff --git a/recipes/squid/squid/squid.init b/recipes/squid/squid/squid.init
--- a/recipes/squid/squid/squid.init
+++ b/recipes/squid/squid/squid.init
@@ -3,7 +3,7 @@ DAEMON=/usr/sbin/squid
 NAME=squid
 DESC="Squid HTTP proxy"
 PIDFILE=/var/run/squid.pid
-SQUID_ARGS="-D -sYC"
+SQUID_ARGS="-D -sY"
 
 test -f $DAEMON || exit 0
 
@@ -36,11 +36,25 @@ start() {
         chown $owner $ldr
     fi
 
-    start-stop-daemon -S -p $PIDFILE -x $DAEMON
+    start-stop-daemon -S -p $PIDFILE -x $DAEMON -- $SQUID_ARGS
 }
 
 stop() {
-        start-stop-daemon -K -p $PIDFILE -x $DAEMON
+	EX=0
+	CNT=1
+	while [ $EX -eq 0 -a $CNT -lt 15 ]; do
+		echo -n .
+		sleep 1
+		start-stop-daemon -K -p $PIDFILE 1>/dev/null 2>&1
+		EX=$?
+		CNT=`expr $CNT + 1`
+	done
+	if [ $CNT -eq 15 ]; then
+		echo "failed."
+	else
+		echo "done."
+		rm -f $PIDFILE
+	fi
 }
 
 case "$1" in
@@ -50,9 +64,8 @@ case "$1" in
         echo "done."
        ;;
     stop)
-        echo -n "Stopping $DESC: $NAME... "
+        echo -n "Stopping $DESC: $NAME"
         stop
-        echo "done."
         ;;
     restart)
         echo "Restarting $DESC: $NAME... "
